### ISSUE TITLE
Code to create the data

### ISSUE THREAD

**Issue by arianhosseini** [facebookresearch/LAMA#13]
Hi all,

Is the code to create the sentences from KBs available? e.g. the code with the templating and the code to generate the sentences with [MASK]?

Thanks,
Arian

**Comment by fabiopetroni** [comment]
Hey Arian,
 
The templates for TREX are available in the zip with the data (relations.jsonl), https://dl.fbaipublicfiles.com/LAMA/data.zip
The templates for Google-RE are here https://github.com/facebookresearch/LAMA/blob/master/scripts/run_experiments.py#L172
 
Ciao,
Fabio

**Comment by Ricocotam** [comment]
Hey,
What about ConceptNet data ? 
Script doesn't seem too hard but it is not clear whether you used full sentences or just free text ones. And if you found some optimisations to make the search faster.

Thanks in advance,
Adrien
