### ISSUE TITLE
How to load a huggingface RoBERTa checkpoint?

### ISSUE THREAD

**Issue by ruizewang** [facebookresearch/LAMA#15]
Hello,
Thanks for your great job. 
I have one problem. I saw in the project, the "roberta_connector.py" load a FAIRSEQ RoBERTa, but I want to load huggingface RoBERTa.  What should I do? Could you give me some advice?
Thanks a lot.

**Comment by fabiopetroni** [comment]
Hey @ruizewang,

sorry for the delay in getting back to you.
Currently we support only the fairseq version of RoBERTa.
It would be great if you decide to implement an HF RoBERTa connector. It should be pretty easy - you can look at the BERT connector for reference. :)

**Comment by ruizewang** [comment]
> Hey @ruizewang,
> 
> sorry for the delay in getting back to you.
> Currently we support only the fairseq version of RoBERTa.
> It would be great if you decide to implement an HF RoBERTa connector. It should be pretty easy - you can look at the BERT connector for reference. :)

Thanks for your help~ Yeah, I already implemented an HF RoBERTa connector, a little modifying from BERT connector.
