### ISSUE TITLE
RoBERTa mean P@1 for LAMA-T-REx and LAMA-Google-RE?

### ISSUE THREAD

**Issue by ruizewang** [facebookresearch/LAMA#16]
Hello,
Have you ever evaluated RoBERTa on LAMA-T-REx and LAMA-Google-RE?

**Comment by fabiopetroni** [comment]
Hey @ruizewang,

yes. I think the results are more or less on par with BERT (probably slightly worse when you aggregate all the relations).
What are you getting?

**Comment by ruizewang** [comment]
> Hey @ruizewang,
> 
> yes. I think the results are more or less on par with BERT (probably slightly worse when you aggregate all the relations).
> What are you getting?

Hello @fabiopetroni, I got the same result as yours, Roberta performs worse than BERT, haha😁. Thanks for your quick reply.
