### ISSUE TITLE
Negated templates for T-REx?

### ISSUE THREAD

**Issue by gabrielilharco** [facebookresearch/LAMA#19]
Hi,

When trying to run experiments, I'm getting errors in T-Rex regarding "template_negated" (full error below). It seems the file `relations.jsonl` contains a bunch of examples where the key "template" is present but the key "template_negated" is not, which makes this part of the code (in run_experiments.py) fail:

```
if "template" in relation:
    PARAMETERS["template"] = relation["template"]
    PARAMETERS["template_negated"] = relation["template_negated"]
```

Is the file `relations.jsonl` missing these keys?

Thanks!

-----------------------------------------------------------------------
Error + relation print:
```
2. T-REx
bert_base
{'description': 'most specific known '
                '(e.g. city instead of '
                'country, or hospital '
                'instead of city) birth '
                'location of a person, '
                'animal or fictional '
                'character',
 'label': 'place of birth',
 'relation': 'P19',
 'template': '[X] was born in [Y] .',
 'type': 'N-1'}
Traceback (most recent call last):
  File "scripts/run_experiments.py", line 215, in <module>
    run_all_LMs(parameters)
  File "scripts/run_experiments.py", line 204, in run_all_LMs
    run_experiments(*parameters, input_param=ip, use_negated_probes=True)
  File "scripts/run_experiments.py", line 114, in run_experiments
    PARAMETERS["template_negated"] = relation["template_negated"]
KeyError: 'template_negated'
```

**Comment by fabiopetroni** [comment]
Hey, you need to download this version of the data https://dl.fbaipublicfiles.com/LAMA/negated_data.tar.gz

**Comment by gabrielilharco** [comment]
Works like a charm, thank you! 

I'm closing this, but maybe it's worth changing the default for `use_negated_probes` in `run_all_LMs` to False? That way the code can be smoothly run from the steps 1-4 in the README.

Currently it's like this:
```
def run_all_LMs(parameters):
    for ip in LMs:
        print(ip["label"])
        run_experiments(*parameters, input_param=ip, use_negated_probes=True)
```
Another option would be to also download and extract the negated_data.tar.gz in the initial steps.
Thanks again for the response!

**Comment by fabiopetroni** [comment]
thanks, fixed
