### ISSUE TITLE
No Matching distribution found for torch

### ISSUE THREAD

**Issue by mathieugrasland** [facebookresearch/LAMA#35]
Hi everyone,

I want to install Lama on my WIN10 laptop and this error keep interrupt:
![image](https://user-images.githubusercontent.com/54704295/83350357-d9299380-a33b-11ea-835e-98c7d8913d26.png)
Can you help me ?

Thanks

Mathieu

**Comment by fabiopetroni** [comment]
Hey Mathieu, did you created a lama specific conda environment? (there are instructions in the README for that)
It might clash with other dependencies you have on your standard environmend.

**Comment by mathieugrasland** [comment]
Thank you for your answer,
At first I didn't tried because it was to be optional...
So I just tried, how to be sure that the conda environment is activated ?
![image](https://user-images.githubusercontent.com/54704295/83352251-8a372a80-a34a-11ea-9914-2eb351bbcf18.png)
I think it is, but still the same error...

**Comment by mathieugrasland** [comment]
Ok I did manage to pass this step, you will have to install before and separatly torch 1.0.1
https://pytorch.org/get-started/previous-versions/ 
for more details : https://github.com/pytorch/pytorch/issues/18384
