### ISSUE TITLE
Running setup.py install for fastBPE ... error

### ISSUE THREAD

**Issue by mathieugrasland** [facebookresearch/LAMA#36]
It seems that I struggle with the requirements step ;
fastBPE and fairseq are the last 2 module to installed and I run into a problem :

![image](https://user-images.githubusercontent.com/54704295/83356435-74376300-a366-11ea-8fd1-1598906e696a.png)

How to fix that ?

Thank you for your time,

Mathieu

**Comment by mathieugrasland** [comment]
I am on WIN10,
I created a conda env only for lama, this errors appears with using
pip install -r requirements.txt
I have seen that maybe fastBPE isn't compatible with Windows, any windows users here?
If you are not a Windows user, maybe you have a clue?

**Comment by fabiopetroni** [comment]
If you are only interested in using BERT, you can avoid installing BPE and
fairseq

**Comment by mathieugrasland** [comment]
Okay thank you,
Do I need to modify requirements.txt to do that ?

**Comment by mathieugrasland** [comment]
Hi @fabiopetroni thank you for your anwser,

So I removed the fairseq requirement in the .txt
The setup works, but then when I try to do : 
`python lama/eval_generation.py --lm "bert" --t "The theory of relativity was developed by [MASK] ."`
![image](https://user-images.githubusercontent.com/54704295/83436110-9cde5c00-a43d-11ea-8432-aa67c7ddaa1d.png)

It seems that fairseq is needed...

**Comment by fabiopetroni** [comment]
Comment out everything inside roberta connector + all other connectors with
issues. If you are exclusively interested in BERT.

**Comment by fabiopetroni** [comment]
@mathieugrasland to clarify, you need to comment out all the code in this file (or simply delete it) without deleting the file. https://github.com/facebookresearch/LAMA/blob/master/lama/modules/roberta_connector.py

You need to do the same for all others problematic files. I hope BERT is not among those.

**Comment by mathieugrasland** [comment]
I just tried...and it works! I had to modify the init python file and comment everything linked to roberta! So much thanks!
