### ISSUE TITLE
KG evaluation datasets?

### ISSUE THREAD

**Issue by matt-peters** [facebookresearch/LAMA#4]
Nice work on the EMNLP paper "Language Models as Knowledge Bases?", and thanks for making the code available.

Are the datasets available to reproduce the results from the paper, namely Table 2?

**Comment by fabiopetroni** [comment]
Thanks for the message @matt-peters. I'm working on that, it will be out soon.

**Comment by matt-peters** [comment]
Excellent, looking forward to it.

**Comment by fabiopetroni** [comment]
The dataset for the LAMA probe is out :)
