### ISSUE TITLE
TREx directory does not exist in the dataset

### ISSUE THREAD

**Issue by ikuyamada** [facebookresearch/LAMA#9]
[`run_experiments.py` uses `TREx` directory](https://github.com/facebookresearch/LAMA/blob/master/scripts/run_experiments.py#L166) which does not exist in the publicized dataset (data.zip). Also, the dataset contains `TREx_alpaca` directory. Is it OK to change the directory name in this line to `TREx_alpaca` to run experiments?

**Comment by fabiopetroni** [comment]
Thanks @ikuyamada for pointing this out. I updated the data.zip archive and renamed that folder :)
